apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSource
metadata:
  name: sta-marketplace-config
spec:
  backends:
  - type: git
    uri: https://github.com/spuchol81/sta-config
    defaultLabel: main
    searchPaths:
    - sta
    - sta-marketplace
---
apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSlice
metadata:
  name: sta-marketplace-config
spec:
  interval: 30s
  configurationSource: sta-marketplace-config
  content:
  - application/default
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: sta-marketplace-config
spec:
  ref:
    apiVersion: config.apps.tanzu.vmware.com/v1alpha4
    kind: ConfigurationSlice
    name: sta-marketplace-config
